---
params:
  name: Baby Yoda
  survey_link: https://giphy.com/clips/baby-yoda-PENDxkjEqGPfxmmcFg
output: md_document
---

Sehr geehrte/r `r params$name`,

Wir haben Ihnen am [DATUM] ein individuelles Feedback und Anleitungen zur Transparenz Ihrer klinischen Studie bzw. Ihren klinischen Studien gegeben und Sie in dieser anonymen, 5-minütigen Umfrage um Ihre Meinung zu den Materialien gebeten: [`r params$survey_link`](`r params$survey_link`).

Einige [#] Ihrer Charité-Kolleg:innen haben bereits ihre Meinung zu der Report Card und dem Infosheet geäußert. Falls Sie es noch nicht getan haben, möchten wir Sie hiermit bitten, die kurze Umfrage auszufüllen, bevor sie **morgen** abläuft.

Wir freuen uns über Ihr Feedback, das uns helfen wird, diese Materialien zu verbessern, die möglicherweise für zukünftige Studien der Charité oder anderer deutscher Universitätskliniken übernommen werden.

Sollten für Ihre Studie(n) Verbesserungsmöglichkeiten bestehen, die wir empfehlen, zeigt Ihnen die Report Card diese auf. Wir werden in 6 Wochen im Rahmen unserer erwähnten Pilotstudie eine weitere Evaluation der Transparenz Ihrer Studie durchführen.

Wir danken Ihnen für Ihre Mitarbeit.

```{r, child="signature-email.Rmd"}
```
